- name: Install BlobFuse2 and configure network on Rocky 9.3 Kubernetes nodes
  hosts: all
  become: true
  tasks:
    # 安装 BlobFuse2
    - name: Add Microsoft repository for RHEL 9
      command:
        cmd: rpm -Uvh https://packages.microsoft.com/config/rhel/9/packages-microsoft-prod.rpm
        creates: /etc/yum.repos.d/microsoft-prod.repo

    - name: Install BlobFuse2
      dnf:
        name: blobfuse2
        state: present

    - name: Install dependencies for BlobFuse2
      dnf:
        name:
          - jq
        state: present
    - name: Create symlink for blobfuse compatibility
      file:
        src: /usr/bin/blobfuse2
        dest: /usr/bin/blobfuse
        state: link
- name: Deploy Azure Blob CSI driver with Secret on Kubernetes nodes
  hosts: localhost  # 在控制节点运行，或指定 kubernetes_nodes 并确保 kubectl/helm 已安装
  become: false
  vars:
    azure_json_path: "./blobfuse/azure.json"  # 替换为实际路径
    secret_name: "azure-cloud-provider"
    secret_namespace: "kube-system"
    helm_repo_name: "blob-csi-driver"
    helm_repo_url: "https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts"
    helm_release_name: "blob-csi-driver"
    helm_chart: "blob-csi-driver/blob-csi-driver"
    helm_version: "1.25.1"

  tasks:
    - name: Generate base64 encoded cloud-config from azure.json
      shell:
        cmd: "cat {{ azure_json_path }} | base64 | awk '{printf $0}'"
      register: cloud_config_base64
      changed_when: false

    - name: Create azure-cloud-provider Secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ secret_name }}"
            namespace: "{{ secret_namespace }}"
          type: Opaque
          data:
            cloud-config: "{{ cloud_config_base64.stdout }}"
      delegate_to: localhost  # 在控制节点运行 kubectl

    - name: Add Helm repository for Blob CSI driver
      kubernetes.core.helm_repository:
        name: "{{ helm_repo_name }}"
        repo_url: "{{ helm_repo_url }}"
      delegate_to: localhost

    - name: Install Blob CSI driver with Helm
      kubernetes.core.helm:
        name: "{{ helm_release_name }}"
        chart_ref: "{{ helm_chart }}"
        release_namespace: "{{ secret_namespace }}"
        chart_version: "{{ helm_version }}"
        set_values:
          node.enableBlobfuseProxy: true
          controller.cloudConfigSecretName: "{{ secret_name }}"
          controller.cloudConfigSecretNamesapce: "{{ secret_namespace }}"
          node.cloudConfigSecretName: "{{ secret_name }}"
          node.cloudConfigSecretNamesapce: "{{ secret_namespace }}"
      delegate_to: localhost
